name: Update Calendar

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install requests beautifulsoup4 pytz rapidfuzz

    - name: Run generator
      run: python generate_calendar.py

    - name: Debug files
      run: ls -lah

    - name: Commit changes
      run: |
        git config user.name "calendar-bot"
        git config user.email "bot@example.com"

        git add calendar.ics

        if git diff --staged --quiet; then
          echo "No changes"
        else
          git commit -m "Auto-update calendar"
          git push
        fi

